<?php
/**
* @file
* Provides a means for a user to record their blood sugar levels once per hour.
*/
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function blood_sugar_monitor_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.blood_sugar_monitor':
            return t('
                <h1>BSM Help</h1>
            ');
            break;
    }
}
