<?php

/**
 * @file
 * Installation functions for blood sugar monitor module.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 */
function blood_sugar_monitor_install() {
    user_role_change_permissions(RoleInterface::AUTHENTICATED_ID, array(
      'store bsm data' => TRUE,
    ));
    user_role_change_permissions(RoleInterface::AUTHENTICATED_ID, array(
      'view bsm data' => TRUE,
    ));
}
